### ISSUE TITLE
从Mania模拟器找来的.

### ISSUE THREAD

**Issue by yty** [fancyzero/fancyzero.github.io#1]
作者你好，我想自己尝试做个节奏游戏，但是没有制谱的天赋。所以想借用Mania里得曲目，不知道ojm格式有没有解析规则？

**Comment by fancyzero** [comment]
那么多 bms的谱不香么

**Comment by yty** [comment]
> 那么多 bms的谱不香么

还真不知道bms谱...多谢你的提示，我去研究下看看。
